apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
  name: condescending-gates-936001
spec:
  charts:
    - axes:
        - base: "10"
          name: x
          scale: linear
        - name: "y"
          scale: linear
      colorizeRows: true
      colors:
        - hex: "#00C9FF"
          id: base
          name: laser
          type: text
      decimalPlaces: 2
      height: 4
      hoverDimension: auto
      kind: Single_Stat_Plus_Line
      legendColorizeRows: true
      legendOpacity: 1
      legendOrientationThreshold: 1e+08
      name: BTC-USD
      opacity: 1
      orientationThreshold: 1e+08
      position: overlaid
      queries:
        - query: |-
            from(bucket: "ticker")
              |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
              |> filter(fn: (r) => r["_measurement"] == "tick")
              |> filter(fn: (r) => r["_field"] == "price")
              |> filter(fn: (r) => r["product"] == "BTC-USD")
      staticLegend:
        colorizeRows: true
        opacity: 1
        orientationThreshold: 1e+08
        widthRatio: 1
      width: 4
      widthRatio: 1
      xCol: _time
      yCol: _value
    - axes:
        - base: "10"
          name: x
          scale: linear
        - name: "y"
          scale: linear
      colorizeRows: true
      colors:
        - hex: "#00C9FF"
          id: base
          name: laser
          type: text
      decimalPlaces: 2
      height: 4
      hoverDimension: auto
      kind: Single_Stat_Plus_Line
      legendColorizeRows: true
      legendOpacity: 1
      legendOrientationThreshold: 1e+08
      name: ETH-USD
      opacity: 1
      orientationThreshold: 1e+08
      position: overlaid
      queries:
        - query: |-
            from(bucket: "ticker")
              |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
              |> filter(fn: (r) => r["_measurement"] == "tick")
              |> filter(fn: (r) => r["_field"] == "price")
              |> filter(fn: (r) => r["product"] == "ETH-USD")
      staticLegend:
        colorizeRows: true
        opacity: 1
        orientationThreshold: 1e+08
        widthRatio: 1
      width: 4
      widthRatio: 1
      xCol: _time
      yCol: _value
      yPos: 4
  name: Tickers
